### ISSUE TITLE
Library does not compile

### ISSUE THREAD

**Issue by HeikkiHietala** [connornishijima/Cartridge#7]
Testing the compile on both 1.8.19 and 2.3.4 yields this error:

C:\Users\heikki.hietala\AppData\Local\Temp\.arduinoIDE-unsaved20241126-7652-16h5jys.7h9yf\NES_DEMO\Cartridge.cpp: In member function 'void Cartridge::init()':
C:\Users\heikki.hietala\AppData\Local\Temp\.arduinoIDE-unsaved20241126-7652-16h5jys.7h9yf\NES_DEMO\Cartridge.cpp:23:3: error: 'sigmaDeltaSetup' was not declared in this scope; did you mean 'sigmaDeltaDetach'?
   23 |   sigmaDeltaSetup(p1_pin, p1_channel, 88200);
      |   ^~~~~~~~~~~~~~~
      |   sigmaDeltaDetach

exit status 1

Compilation error: 'sigmaDeltaSetup' was not declared in this scope; did you mean 'sigmaDeltaDetach'?

Please advise.

**Comment by jeason1997** [comment]
Cartridge.cpp：

void Cartridge::init(){
  // sigmaDeltaSetup(p1_pin, p1_channel, 88200);
  // sigmaDeltaWrite(p1_channel, 0);

  // sigmaDeltaSetup(p2_pin, p2_channel, 88200);
  // sigmaDeltaWrite(p2_channel, 0);

  // sigmaDeltaSetup(n_pin, n_channel, 88200);
  // sigmaDeltaWrite(n_channel, 0);

  // sigmaDeltaSetup(t_pin, t_channel, 88200);
  // sigmaDeltaWrite(t_channel, 0);

  ledcAttach(p1_pin, 88200, 8);
  ledcWrite(p1_pin, 128);

  ledcAttach(p2_pin, 88200, 8);
  ledcWrite(p2_pin, 128);

  ledcAttach(n_pin, 88200, 8);
  ledcWrite(n_pin, 128);

  ledcAttach(t_pin, 88200, 8);
  ledcWrite(t_pin, 128);
}


void Cartridge::render_audio(){
  // four channel
 
  // sigmaDeltaWrite(p1_channel, p1_output * 12);
  // sigmaDeltaWrite(p2_channel, p2_output * 12);
  // sigmaDeltaWrite(n_channel, n_output * 6);
  // sigmaDeltaWrite(t_channel, t_output * 16);


  uint8_t val1 = constrain(128 + (p1_output * 12), 0, 255);
  uint8_t val2 = constrain(128 + (p2_output * 12), 0, 255);
  uint8_t valn = constrain(128 + (n_output * 6),  0, 255);
  uint8_t valt = constrain(128 + (t_output * 16), 0, 255);
  ledcWrite(p1_pin, val1);
  ledcWrite(p2_pin, val2);
  ledcWrite(n_pin, valn);
  ledcWrite(t_pin, valt);

  // single channel
  /*
  uint8_t sum = 0;
  sum+=p1_output*0.8;
  sum+=p2_output*0.8;
  sum+=n_output*0.7;
  sum+=t_output;
  //sigmaDeltaWrite(t_channel, sum);
  dacWrite(25,sum*1.25);
  */
}
